set DATASTORE_DATASET=strong-surfer-379310
set DATASTORE_EMULATOR_HOST=localhost:8081
set DATASTORE_EMULATOR_HOST_PATH=localhost:8081/datastore
set DATASTORE_HOST=http://localhost:8081
set DATASTORE_PROJECT_ID=strong-surfer-379310

set DATASTORE_USE_PROJECT_ID_AS_APP_ID=true
